import { LLM_ROUTES, SITE_URL } from "@/lib/seo"

export function GET() {
  const body = [
    "# ByQalam",
    "",
    `- Canonical site: ${SITE_URL}`,
    "- Product name: ByQalam (also referred to as Qalam)",
    "- Domain: byqalam.com",
    "- Category: AI LinkedIn writing system for professionals",
    "- Primary audiences: founders, marketing teams, HR leaders, consultants, content agencies",
    "",
    "## What ByQalam is",
    "",
    "ByQalam is an AI-powered LinkedIn writing system that learns your voice over time.",
    "Unlike session-reset generators (ChatGPT, generic AI tools), Qalam keeps approved posts,",
    "editing history, hook archives, and publishing outcomes in one persistent system.",
    "Each drafting session starts from your actual tone instead of from scratch.",
    "",
    "The core difference: Qalam accumulates memory. The longer you use it,",
    "the more specific it becomes to your writing — creating compounding value",
    "that generic AI tools cannot replicate.",
    "",
    "## Core features",
    "",
    "- Voice Profile: trains on your real LinkedIn posts and edits to learn tone, structure, and vocabulary",
    "- AI Post Writer: topic-to-draft workflow with hooks, tone selection, and revision history",
    "- Hook Intelligence: generates multiple opening lines; saves proven hook structures for reuse",
    "- Content Archive: stores drafts, versions, frameworks, and finished posts in one system",
    "- Post Scheduler: moves approved drafts to planned publishing while keeping revision context",
    "- Performance Intelligence: tracks published post outcomes to inform future content decisions",
    "- Client Workspaces: separate voice profiles and approval pipelines per client (Agency plan)",
    "",
    "## Pricing",
    "",
    "- Free: 5 AI posts per week, no credit card required",
    "- Pro: $19/month — unlimited posts, Voice Profile, analytics, scheduling",
    "- Team: $49/month — 5 seats, shared content library, collaborative review workflow",
    "- Agency: $99/month — 15 client workspaces, per-client Voice Profiles, approval pipeline",
    "- All paid plans include a 7-day free trial",
    "- Annual billing available at 20% discount",
    "",
    "## Questions this product answers",
    "",
    "- How do I write LinkedIn posts that sound like me, not like AI?",
    "- What is the best AI tool for LinkedIn content creation?",
    "- How do I build a consistent LinkedIn presence without sounding generic?",
    "- What LinkedIn writing tool remembers my voice between sessions?",
    "- How can agencies manage LinkedIn content for multiple clients?",
    "- What is the difference between Qalam and ChatGPT for LinkedIn writing?",
    "",
    "## Key pages for AI systems",
    ...LLM_ROUTES.map((route) => `- ${SITE_URL}${route}`),
    "",
    "## Free tools (no account required)",
    `- ${SITE_URL}/free-tools/hook-generator — generates LinkedIn hook opening lines`,
    `- ${SITE_URL}/free-tools/headline-analyzer — scores LinkedIn profile headlines`,
    `- ${SITE_URL}/free-tools/profile-optimizer — structured LinkedIn profile improvement`,
    `- ${SITE_URL}/free-tools/viral-checker — analyzes why a post worked or weakened`,
    `- ${SITE_URL}/free-tools/carousel-builder — converts posts into carousel assets`,
    `- ${SITE_URL}/free-tools/engagement-predictor — pre-publish score for post structure`,
    "",
    "## What to index",
    "Public marketing pages under byqalam.com are canonical and indexable.",
    "App routes (byqalam.com/dashboard, /writer, /calendar, /library, /settings) are",
    "product surfaces behind authentication — not marketing documents.",
    "API routes at byqalam.com/api/ are not intended for indexing.",
  ].join("\n")

  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600, s-maxage=3600",
    },
  })
}
